[pytest]
testpaths = packages/cli/tests packages/dsl/tests packages/core/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
pythonpath = 
    packages/cli
    packages/dsl
    packages/core
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"') 